/* X OS compat: ck_queue stub - map CK_* to sys/queue.h equivalents */
#ifndef _CK_QUEUE_H_
#define _CK_QUEUE_H_

#include <sys/queue.h>

#define CK_STAILQ_HEAD STAILQ_HEAD
#define CK_STAILQ_ENTRY STAILQ_ENTRY
#define CK_LIST_HEAD LIST_HEAD
#define CK_LIST_ENTRY LIST_ENTRY
#define CK_SLIST_HEAD SLIST_HEAD
#define CK_SLIST_ENTRY SLIST_ENTRY
#define CK_LIST_INIT LIST_INIT
#define CK_LIST_INSERT_HEAD LIST_INSERT_HEAD
#define CK_LIST_REMOVE LIST_REMOVE
#define CK_LIST_NEXT LIST_NEXT
#define CK_LIST_EMPTY LIST_EMPTY
#define CK_LIST_FIRST LIST_FIRST
#define CK_SLIST_INIT SLIST_INIT
#define CK_SLIST_INSERT_HEAD SLIST_INSERT_HEAD
#define CK_SLIST_REMOVE SLIST_REMOVE
#define CK_SLIST_NEXT SLIST_NEXT
#define CK_SLIST_EMPTY SLIST_EMPTY
#define CK_SLIST_FIRST SLIST_FIRST
#define CK_SLIST_FOREACH SLIST_FOREACH
#define CK_SLIST_FOREACH_SAFE SLIST_FOREACH_SAFE
#define CK_SLIST_HEAD_INITIALIZER SLIST_HEAD_INITIALIZER
#define CK_SLIST_REMOVE_HEAD SLIST_REMOVE_HEAD
#define CK_SLIST_REMOVE_AFTER SLIST_REMOVE_AFTER
#define CK_SLIST_INSERT_AFTER SLIST_INSERT_AFTER
#define CK_LIST_FOREACH LIST_FOREACH
#define CK_LIST_FOREACH_SAFE LIST_FOREACH_SAFE
#define CK_LIST_FOREACH_FROM LIST_FOREACH_FROM
#define CK_LIST_HEAD_INITIALIZER LIST_HEAD_INITIALIZER
#define CK_LIST_INSERT_BEFORE LIST_INSERT_BEFORE
#define CK_LIST_INSERT_AFTER LIST_INSERT_AFTER
#define CK_LIST_SEARCH_HEAD LIST_SEARCH_HEAD
#define CK_STAILQ_INIT STAILQ_INIT
#define CK_STAILQ_INSERT_HEAD STAILQ_INSERT_HEAD
#define CK_STAILQ_INSERT_TAIL STAILQ_INSERT_TAIL
#define CK_STAILQ_REMOVE STAILQ_REMOVE
#define CK_STAILQ_FIRST STAILQ_FIRST
#define CK_STAILQ_NEXT STAILQ_NEXT
#define CK_STAILQ_EMPTY STAILQ_EMPTY
#define CK_STAILQ_FOREACH STAILQ_FOREACH
#define CK_STAILQ_FOREACH_SAFE STAILQ_FOREACH_SAFE
#define CK_STAILQ_CONCAT STAILQ_CONCAT

/* CK PR stubs */
static inline void *ck_pr_load_ptr(void *target) {
    return *(void *volatile *)target;
}

#endif /* _CK_QUEUE_H_ */
